
version: "3"
services:
  example-nats-microservice-nats:
    image: "bitnami/nats:2.10.5"
    container_name: "example-nats-microservice-nats"
    volumes:
      - "example-nats-microservice-nats-volume:/bitnami/nats/data"
    ports:
      - "8222:8222"
      - "4222:4222"
    networks:
      - "example-nats-microservice-network"
    environment:
      NATS_ENABLE_AUTH: "yes"
      NATS_USERNAME: "natsadmin"
      NATS_PASSWORD: "6EcbcW66JsKvFrY2bZw6QGKjHhefca7Kgpp1"
      NATS_EXTRA_ARGS: "-js"
    tty: true
    restart: "always"
networks:
  example-nats-microservice-network:
    driver: "bridge"
volumes:
  example-nats-microservice-nats-volume:
    name: "example-nats-microservice-nats-volume"
